export const TBK_GOODS_GETINFO = 'TBK_GOODS_GETINFO'
export const TBK_GOODS_CONVERT = 'TBK_GOODS_CONVERT'
export const TBK_GOODS_TPWD_CREATE = 'TBK_GOODS_TPWD_CREATE'
export const TBK_GOODS_UPDATE_INFO = 'TBK_GOODS_UPDATE_INFO'